language: node_js

node_js:
  - '10.15'

cache:
  - npm: true
  - yarn: true

matrix:
  fast_finish: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.1
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - npm install -g codecov
  - yarn install

before_script:
  - yarn build

script:
  - yarn test

after_script:
  - codecov
